// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

import 'package:ddstudy_ui/domain/db_model.dart';

part 'subscribe_status.g.dart';

@JsonSerializable()
class SubscribeStatus implements DBModel {
  @override
  final String? id;
  final bool isSubscribeRequestSent;
  final bool isFollowing;

  SubscribeStatus({
    required this.isSubscribeRequestSent,
    required this.isFollowing,
    this.id,
  });

  factory SubscribeStatus.fromJson(Map<String, dynamic> json) =>
      _$SubscribeStatusFromJson(json);

  Map<String, dynamic> toJson() => _$SubscribeStatusToJson(this);

  @override
  Map<String, dynamic> toMap() => _$SubscribeStatusToJson(this);

  factory SubscribeStatus.fromMap(Map<String, dynamic> map) => SubscribeStatus(
        id: map['id'] as String?,
        isSubscribeRequestSent:
            map['isSubscribeRequestSent'] == 1 ? true : false,
        isFollowing: map['isFollowing'] == 1 ? true : false,
      );

  SubscribeStatus copyWith({
    String? id,
    bool? isSubscribeRequestSent,
    bool? isFollowing,
  }) {
    return SubscribeStatus(
      id: id ?? this.id,
      isSubscribeRequestSent:
          isSubscribeRequestSent ?? this.isSubscribeRequestSent,
      isFollowing: isFollowing ?? this.isFollowing,
    );
  }
}
