// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'user_activity.g.dart';

@JsonSerializable()
class UserActivity {
  final int postsAmount;
  final int followersAmount;
  final int followingAmount;

  UserActivity({
    required this.postsAmount,
    required this.followersAmount,
    required this.followingAmount,
  });

  factory UserActivity.fromJson(Map<String, dynamic> json) =>
      _$UserActivityFromJson(json);

  Map<String, dynamic> toJson() => _$UserActivityToJson(this);
}
