// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'follow_user_request.g.dart';

@JsonSerializable()
class FollowUserRequest {
  String authorId;

  FollowUserRequest({
    required this.authorId,
  });

  factory FollowUserRequest.fromJson(Map<String, dynamic> json) =>
      _$FollowUserRequestFromJson(json);
  Map<String, dynamic> toJson() => _$FollowUserRequestToJson(this);
}
