// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

import '../user/user.dart';
import 'comment_stats.dart';

part 'comment_model.g.dart';

@JsonSerializable()
class CommentModel {
  String id;
  String text;
  DateTime uploadDate;
  User author;
  CommentStats stats;

  CommentModel({
    required this.id,
    required this.text,
    required this.uploadDate,
    required this.author,
    required this.stats,
  });

  factory CommentModel.fromJson(Map<String, dynamic> json) =>
      _$CommentModelFromJson(json);
  Map<String, dynamic> toJson() => _$CommentModelToJson(this);
}
