// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'comment_post_request.g.dart';

@JsonSerializable()
class CommentPostRequest {
  String postId;
  String text;

  CommentPostRequest({
    required this.postId,
    required this.text,
  });

  factory CommentPostRequest.fromJson(Map<String, dynamic> json) =>
      _$CommentPostRequestFromJson(json);
  Map<String, dynamic> toJson() => _$CommentPostRequestToJson(this);
}
